# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  CI:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v22.2.0]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalação do Mocha e dos pacotes para testes
      run: 
        cd src;
        npm install -g mocha;
        npm install

    - name: Execução dos testes
      run: mocha src/test/convert.js;

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Build e push da imagem Docker
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |          
          vinniciuscruz/aula-conversao-temperatura:v1
          vinniciuscruz/aula-conversao-temperatura:latest

        
